// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kamar": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kamar-controller"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kamar-controller"
                ],
                "parameters": [
                    {
                        "description": "Data Kost",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.KamarRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.KamarResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/kamar/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kamar-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Kamar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Kamar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateKamarRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.KamarResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kamar-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Kamar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    }
                }
            }
        },
        "/kost": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kost-controller"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ViewKostResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kost-controller"
                ],
                "parameters": [
                    {
                        "description": "Data Kost",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddKostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.KostResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/kost/kamar": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kost-controller"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.KamarKostReponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/kost/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kost-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Kost",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Kost",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateKostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.KostResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kost-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Kost",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-controller"
                ],
                "parameters": [
                    {
                        "description": "Data user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.APIResponse"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-controller"
                ],
                "parameters": [
                    {
                        "description": "Data user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.SignUpResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/transaction-booking-cancel/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Booking",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.BookingSaveResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/transaction-booking/users/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Booking",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.BookingResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/transaction-booking/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Booking",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.BookingResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction-controller"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Kost",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Kost",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.BookingSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.BookingSaveResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "request.AddKostRequest": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "namaKost": {
                    "type": "string"
                },
                "pemilik": {
                    "type": "integer"
                },
                "typeKost": {
                    "type": "string"
                }
            }
        },
        "request.BookingSaveRequest": {
            "type": "object",
            "properties": {
                "detailPenghuni": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.PenghuniRequest"
                    }
                },
                "jumlahPenghuni": {
                    "type": "integer"
                },
                "kamarId": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "request.KamarRequest": {
            "type": "object",
            "properties": {
                "hargaKamar": {
                    "type": "integer"
                },
                "kostId": {
                    "type": "integer"
                },
                "namaKamar": {
                    "type": "string"
                },
                "statusKamar": {
                    "type": "string"
                }
            }
        },
        "request.Login": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.PenghuniRequest": {
            "type": "object",
            "properties": {
                "jenisKelamin": {
                    "type": "string"
                },
                "namaPenghuni": {
                    "type": "string"
                },
                "nomorHp": {
                    "type": "integer"
                },
                "nomorKtp": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "roleid": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.UpdateKamarRequest": {
            "type": "object",
            "properties": {
                "hargaKamar": {
                    "type": "integer"
                },
                "kostId": {
                    "type": "integer"
                },
                "statusKamar": {
                    "type": "string"
                }
            }
        },
        "request.UpdateKostRequest": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "namaKost": {
                    "type": "string"
                },
                "pemilik": {
                    "type": "integer"
                },
                "typeKost": {
                    "type": "string"
                }
            }
        },
        "response.BookingResponse": {
            "type": "object",
            "properties": {
                "detailPenghuni": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PenghuniResponse"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "jumlahPenghuni": {
                    "type": "integer"
                },
                "namaKost": {
                    "type": "string"
                },
                "statusBooking": {
                    "type": "string"
                },
                "typeKost": {
                    "type": "string"
                }
            }
        },
        "response.BookingSaveResponse": {
            "type": "object",
            "properties": {
                "detailPenghuni": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PenghuniResponse"
                    }
                },
                "jumlahPenghuni": {
                    "type": "integer"
                },
                "namaKost": {
                    "type": "string"
                },
                "statusBooking": {
                    "type": "string"
                }
            }
        },
        "response.GetKamarResponse": {
            "type": "object",
            "properties": {
                "hargaKamar": {
                    "type": "integer"
                },
                "nomorKamar": {
                    "type": "string"
                },
                "statusKamar": {
                    "type": "string"
                }
            }
        },
        "response.KamarKostReponse": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "detailKamar": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.GetKamarResponse"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "namaKost": {
                    "type": "string"
                },
                "sisaKamar": {
                    "type": "integer"
                },
                "typeKost": {
                    "type": "string"
                }
            }
        },
        "response.KamarResponse": {
            "type": "object",
            "properties": {
                "hargaKamar": {
                    "type": "integer"
                },
                "nomorKamar": {
                    "type": "string"
                },
                "statusKamar": {
                    "type": "string"
                }
            }
        },
        "response.KostResponse": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "namaKost": {
                    "type": "string"
                },
                "pemilik": {
                    "type": "string"
                },
                "typeKost": {
                    "type": "string"
                }
            }
        },
        "response.PenghuniResponse": {
            "type": "object",
            "properties": {
                "jenisKelamin": {
                    "type": "string"
                },
                "namaPenghuni": {
                    "type": "string"
                },
                "nomorHp": {
                    "type": "integer"
                },
                "nomorKtp": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.SignUpResponse": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.ViewKostResponse": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "namaKost": {
                    "type": "string"
                },
                "pemilik": {
                    "type": "string"
                },
                "typeKost": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer \" followed by your JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Aplikasi Booking Kost API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
