basePath: /api
definitions:
  common.APIResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  request.AddKostRequest:
    properties:
      alamat:
        type: string
      namaKost:
        type: string
      pemilik:
        type: integer
      typeKost:
        type: string
    type: object
  request.BookingSaveRequest:
    properties:
      detailPenghuni:
        items:
          $ref: '#/definitions/request.PenghuniRequest'
        type: array
      jumlahPenghuni:
        type: integer
      kamarId:
        type: integer
      userId:
        type: integer
    type: object
  request.KamarRequest:
    properties:
      hargaKamar:
        type: integer
      kostId:
        type: integer
      namaKamar:
        type: string
      statusKamar:
        type: string
    type: object
  request.PenghuniRequest:
    properties:
      jenisKelamin:
        type: string
      namaPenghuni:
        type: string
      nomorHp:
        type: integer
      nomorKtp:
        type: string
      status:
        type: string
    type: object
  request.RegisterRequest:
    properties:
      password:
        type: string
      roleid:
        type: integer
      username:
        type: string
    type: object
  request.UpdateKamarRequest:
    properties:
      hargaKamar:
        type: integer
      kostId:
        type: integer
      statusKamar:
        type: string
    type: object
  request.UpdateKostRequest:
    properties:
      alamat:
        type: string
      namaKost:
        type: string
      pemilik:
        type: integer
      typeKost:
        type: string
    type: object
  response.BookingResponse:
    properties:
      detailPenghuni:
        items:
          $ref: '#/definitions/response.PenghuniResponse'
        type: array
      id:
        type: integer
      jumlahPenghuni:
        type: integer
      namaKost:
        type: string
      statusBooking:
        type: string
      typeKost:
        type: string
    type: object
  response.BookingSaveResponse:
    properties:
      detailPenghuni:
        items:
          $ref: '#/definitions/response.PenghuniResponse'
        type: array
      jumlahPenghuni:
        type: integer
      namaKost:
        type: string
      statusBooking:
        type: string
    type: object
  response.GetKamarResponse:
    properties:
      hargaKamar:
        type: integer
      nomorKamar:
        type: string
      statusKamar:
        type: string
    type: object
  response.KamarKostReponse:
    properties:
      alamat:
        type: string
      detailKamar:
        items:
          $ref: '#/definitions/response.GetKamarResponse'
        type: array
      id:
        type: integer
      namaKost:
        type: string
      sisaKamar:
        type: integer
      typeKost:
        type: string
    type: object
  response.KamarResponse:
    properties:
      hargaKamar:
        type: integer
      nomorKamar:
        type: string
      statusKamar:
        type: string
    type: object
  response.KostResponse:
    properties:
      alamat:
        type: string
      namaKost:
        type: string
      pemilik:
        type: string
      typeKost:
        type: string
    type: object
  response.PenghuniResponse:
    properties:
      jenisKelamin:
        type: string
      namaPenghuni:
        type: string
      nomorHp:
        type: integer
      nomorKtp:
        type: string
      status:
        type: string
    type: object
  response.SignUpResponse:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  response.ViewKostResponse:
    properties:
      alamat:
        type: string
      namaKost:
        type: string
      pemilik:
        type: string
      typeKost:
        type: string
    type: object
info:
  contact: {}
  description: API dokumentasi untuk Aplikasi AdaKost
  title: AdaKost API
  version: "1.0"
paths:
  /kamar:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.APIResponse'
      tags:
      - kamar-controller
    post:
      consumes:
      - application/json
      parameters:
      - description: Data Kost
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.KamarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KamarResponse'
              type: object
      tags:
      - kamar-controller
  /kamar/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID Kamar
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.APIResponse'
      tags:
      - kamar-controller
    put:
      consumes:
      - application/json
      parameters:
      - description: ID Kamar
        in: path
        name: id
        required: true
        type: integer
      - description: Data Kamar
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateKamarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KamarResponse'
              type: object
      tags:
      - kamar-controller
  /kost:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ViewKostResponse'
              type: object
      tags:
      - kost-controller
    post:
      consumes:
      - application/json
      parameters:
      - description: Data Kost
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.AddKostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KostResponse'
              type: object
      tags:
      - kost-controller
  /kost/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID Kost
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.APIResponse'
      tags:
      - kost-controller
    put:
      consumes:
      - application/json
      parameters:
      - description: ID Kost
        in: path
        name: id
        required: true
        type: integer
      - description: Data Kost
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateKostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KostResponse'
              type: object
      tags:
      - kost-controller
  /kost/kamar:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KamarKostReponse'
              type: object
      tags:
      - kost-controller
  /signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Data user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.SignUpResponse'
              type: object
      tags:
      - user-controller
  /transaction-booking-cancel/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID Booking
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.BookingSaveResponse'
              type: object
      tags:
      - transaction-controller
  /transaction-booking/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID Booking
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.BookingResponse'
              type: object
      tags:
      - transaction-controller
    post:
      consumes:
      - application/json
      parameters:
      - description: ID Kost
        in: path
        name: id
        required: true
        type: integer
      - description: Data Kost
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.BookingSaveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.BookingSaveResponse'
              type: object
      tags:
      - transaction-controller
  /transaction-booking/users/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID Booking
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.BookingResponse'
              type: object
      tags:
      - transaction-controller
swagger: "2.0"
